# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19965491b28943738066f276cc430f9e5bb1c27e9a82f1ca1e136bc4623c2384b60792158b9d141cc5b182a75dc2527769ee22280f10bc5420c3908e275f260b

test:
  secret_key_base: f1e8f1a7fa38d554908933b66ba3a2b927bfb7115f27de6ce92939ef2fd01c1e85fa0eb89e050177ae1189d6187349f073e55edbdd17c34ce4b0189a0052e68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
